# Generated by Django 5.2.10 on 2026-01-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('socks4', 'SOCKS4'), ('socks5', 'SOCKS5')], default='http', max_length=10)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('score', models.IntegerField(default=10, help_text='Score from 0 to 100')),
                ('speed', models.IntegerField(default=0, help_text='Response time in ms')),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', '-speed'],
                'unique_together': {('ip', 'port', 'protocol')},
            },
        ),
    ]
