# Generated by Django 5.2.10 on 2026-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='source',
            field=models.CharField(default='proxifly', max_length=50),
        ),
    ]
