# Generated by Django 5.2.10 on 2026-01-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proxy_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='anonymity',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
